apiVersion: v1
kind: ConfigMap
metadata:
  name: tc-app-config
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "mysql"
  DB_PORT: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: tc-app-secret
type: Opaque
stringData:
  DB_HOST: "tc-db-mysql.cqxe3cv5beda.us-east-1.rds.amazonaws.com" # Preenchido automaticamente ou manualmente
  DB_DATABASE: "techchallenge"
  DB_USERNAME: "dbadmin"
  DB_PASSWORD: "secretpassword"
  JWT_SECRET: "SEU_JWT_SECRET"