name: Deploy K8s Infrastructure via Terraform

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    name: Apply Infrastructure with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Apply K8s Manifests via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Cria/limpa uma pasta temporária na EC2
            rm -rf ~/k8s-manifests && mkdir -p ~/k8s-manifests
            
            # 2. Clona o repositório ou baixa os arquivos usando o token do GitHub
            git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ~/repo-temp
            
            # 3. Copia a pasta de manifestos para o diretório local
            cp -r ~/repo-temp/k8s-manifests/* ~/k8s-manifests/
            rm -rf ~/repo-temp

            # 4. Aplica os arquivos YAML diretamente pelo caminho local no K3s
            sudo k3s kubectl apply -f ~/k8s-manifests/