name: Deploy K8s Infrastructure via Terraform

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    name: Apply Infrastructure with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Apply K8s Manifests via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Instala dependências básicas (git) no Amazon Linux 2023
            sudo dnf install -y git

            # 2. Instala o K3s (se ainda não estiver instalado)
            if ! command -v k3s &> /dev/null; then
              echo "K3s não encontrado. Instalando..."
              curl -sfL https://get.k3s.io | sh -
              # Aguarda o serviço do K3s inicializar completamente
              sleep 10
            fi

            # 3. Prepara a pasta de manifestos
            rm -rf ~/k8s-manifests ~/repo-temp
            mkdir -p ~/k8s-manifests

            # 4. Clona o repositório
            git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/william-moura/tc-soat-k8s-infra.git ~/repo-temp

            # 5. Copia os manifestos e limpa a pasta temporária
            cp -r ~/repo-temp/k8s-manifests/* ~/k8s-manifests/
            rm -rf ~/repo-temp

            # 6. Aplica os manifestos no K3s
            sudo k3s kubectl apply -f ~/k8s-manifests/