name: Apply K8s Manifests to Hostinger VPS

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Manifests via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_IP }}
          username: root
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

            # 1. Garantir que o namespace do projeto existe
            k3s kubectl create namespace oficina-mecanica --dry-run=client -o yaml | k3s kubectl apply -f -

            # 2. Clonar/Atualizar os manifestos na VPS e aplicar
            rm -rf ~/k8s-manifests && mkdir -p ~/k8s-manifests
            git clone https://github.com/william-moura/tc-soat-k8s-infra.git ~/k8s-manifests
            
            # 3. Aplicar os manifestos dentro do namespace oficina-mecanica
            k3s kubectl apply -f ~/k8s-manifests/k8s-manifests/ -n oficina-mecanica
            rm -rf ~/k8s-manifests